version: 2.1

orbs:
  base: dmx-io/base@2.0.88
  slack: circleci/slack@4.4.2

jobs:
  build_hop_node:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      DOCKER_IMAGE=hopprotocol/hop-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update
            apk upgrade
            apk add --no-cache curl
            apk add --no-cache jq
            apk add --no-cache py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            cd packages/hop-node
            docker build \
              -f Dockerfile \
              --no-cache \
              -t app .
      - deploy:
          name: Push Hop Node Docker image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            export BRANCH=$(echo $CIRCLE_BRANCH | sed 's/\//-/g')
            docker tag app $DOCKER_IMAGE:$CIRCLE_SHA1
            docker tag app $DOCKER_IMAGE:$BRANCH
            docker push $DOCKER_IMAGE:$CIRCLE_SHA1
            docker push $DOCKER_IMAGE:$BRANCH
            test $BRANCH == "mainnet-bonder" && docker tag app $DOCKER_IMAGE:latest && docker push $DOCKER_IMAGE:latest; true
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  main:
    jobs:
      - build_hop_node:
          filters:
            branches:
              only:
                - production
                - staging
                - mainnet
                - mainnet-bonder
                - ropsten
                - rinkeby
                - kovan
                - goerli
              ignore: /.*/