[build]
  base    = "packages/frontend/"
  command = "yarn build"
  publish = "build/"

[[redirects]]
  from = "/*"
  to = "/451.html"
  status = 451
  force = true
  conditions = {Country=["BY","CU","IR","IQ","CI","LR","KP","SD","SY","ZW"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=15780000; includeSubDomains; preload"
    Feature-Policy = "geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker-selection 'none'; fullscreen 'none'; payment 'none'"
